#!/bin/sh
cd reconstruction
python generation_audiotransformer_VGGsound_decoded_features.py config/recon_vggsound_fmriprep_rep4_500voxel_vggishish_allunits_fastl2lir_alpha100.yaml
python generation_audiotransformer_VGGsound_decoded_features.py config/recon_vggsound_attention_fmriprep_rep4_500voxel_vggishish_allunits_fastl2lir_alpha100.yaml