analysis name: vggsound_fmriprep_rep4_500voxel_allunits_fastl2lir_alpha100

# fMRI data ##################################################################
training fmri:
  S1:
    - ../data/fmri_data/S1_VGGishishTrain_volume_native.h5    
  S2:
    - ../data/fmri_data/S2_VGGishishTrain_volume_native.h5    
  S3:
    - ../data/fmri_data/S3_VGGishishTrain_volume_native.h5    
  S4:
    - ../data/fmri_data/S4_VGGishishTrain_volume_native.h5    
  S5:
    - ../data/fmri_data/S5_VGGishishTrain_volume_native.h5    

test fmri:
  S1:
    - ../data/fmri_data/S1_VGGishishTest_volume_native.h5    
  S2:
    - ../data/fmri_data/S2_VGGishishTest_volume_native.h5    
  S3:
    - ../data/fmri_data/S3_VGGishishTest_volume_native.h5    
  S4:
    - ../data/fmri_data/S4_VGGishishTest_volume_native.h5    
  S5:
    - ../data/fmri_data/S5_VGGishishTest_volume_native.h5    

# The ROIs used in feature decoding
rois:
  AC : hcp180_r_lh.L_A1_ROI = 1 | hcp180_r_lh.L_MBelt_ROI = 1 | hcp180_r_lh.L_PBelt_ROI = 1 | hcp180_r_lh.L_RI_ROI = 1 | hcp180_r_lh.L_A4_ROI = 1 | hcp180_r_lh.L_A5_ROI = 1 | hcp180_r_lh.L_STSdp_ROI = 1 | hcp180_r_lh.L_STSda_ROI = 1 | hcp180_r_lh.L_STSvp_ROI = 1 | hcp180_r_lh.L_STSva_ROI = 1 | hcp180_r_lh.L_STGa_ROI = 1 | hcp180_r_lh.L_TA2_ROI = 1 | hcp180_r_rh.R_A1_ROI = 1 | hcp180_r_rh.R_MBelt_ROI = 1 | hcp180_r_rh.R_PBelt_ROI = 1 | hcp180_r_rh.R_RI_ROI = 1 | hcp180_r_rh.R_A4_ROI = 1 | hcp180_r_rh.R_A5_ROI = 1 | hcp180_r_rh.R_STSdp_ROI = 1 | hcp180_r_rh.R_STSda_ROI = 1 | hcp180_r_rh.R_STSvp_ROI = 1 | hcp180_r_rh.R_STSva_ROI = 1 | hcp180_r_rh.R_STGa_ROI = 1 | hcp180_r_rh.R_TA2_ROI | hcp180_r_lh.L_LBelt_ROI = 1 | hcp180_r_rh.R_LBelt_ROI = 1 
  A1 :  hcp180_r_lh.L_A1_ROI = 1  |  hcp180_r_rh.R_A1_ROI = 1 
  LBelt : hcp180_r_lh.L_LBelt_ROI = 1 | hcp180_r_rh.R_LBelt_ROI = 1
  PBelt : hcp180_r_lh.L_PBelt_ROI = 1  | hcp180_r_rh.R_PBelt_ROI = 1 
  A4 : hcp180_r_lh.L_A4_ROI = 1  | hcp180_r_rh.R_A4_ROI = 1 
  A5 : hcp180_r_lh.L_A5_ROI = 1  | hcp180_r_rh.R_A5_ROI = 1 
  # MBelt : hcp180_r_lh.L_MBelt_ROI = 1  | hcp180_r_rh.R_MBelt_ROI = 1 
  # RI : hcp180_r_lh.L_RI_ROI = 1  | hcp180_r_rh.R_RI_ROI = 1 
  # STSdp : hcp180_r_lh.L_STSdp_ROI = 1  | hcp180_r_rh.R_STSdp_ROI = 1 
  # STSda : hcp180_r_lh.L_STSda_ROI = 1  | hcp180_r_rh.R_STSda_ROI = 1 
  # STSvp : hcp180_r_lh.L_STSvp_ROI = 1  | hcp180_r_rh.R_STSvp_ROI = 1
  # STSva : hcp180_r_lh.L_STSva_ROI = 1  | hcp180_r_rh.R_STSva_ROI = 1
  # STGa : hcp180_r_lh.L_STGa_ROI = 1 | hcp180_r_rh.R_STGa_ROI = 1
  # TA2 : hcp180_r_lh.L_TA2_ROI = 1 | hcp180_r_rh.R_TA2_ROI = 1 

# The number of voxels used in feature decoding
rois voxel num:
  AC : 500
  A1 : 200
  LBelt : 200
  PBelt : 200
  A4 : 200
  A5 : 200 
  # MBelt : 200
  # RI : 200
  # STSdp : 200 
  # STSda : 200
  # STSvp : 200
  # STSva : 200
  # STGa : 200
  # TA2 : 200

# In feature decoding, the key label is used for matching the DNN features. 
label key:
  sample_name

# DNN features ###############################################################
training feature dir:
  - ../data/features/VGGishishTrain/

test feature dir:
  - ../data/features/VGGishishTest/

network:
  vggishish/vggsound_4sec_crop

layers:
  # - conv1_1
  # - conv2_1
  # - conv3_1
  # - conv4_1
  - conv5_3
  # - fc3
  # - mel
  # - modulation

# Feature decoding ###########################################################
feature decoder dir:
  ../data/feature_decoders/VGGishish/sound_recon

# Decoded features
decoded feature dir:
  ../data/decoded_features/VGGishish/sound_recon

test average num:
  8

# Learning parameters
alpha: 100
chunk axis: 1

# Figure output
decoding figure dir:
  ../data/figures
